version: '3'
services:
  deps:
    build:
      context: ./
      dockerfile: Dockerfile-integration
    volumes:
      - "./:/go/src/github.com/aunem/transpose"
    command: dep ensure
    working_dir: /go/src/github.com/aunem/transpose
  build:
    build:
      context: ./
      dockerfile: Dockerfile-integration
    volumes:
      - "./:/go/src/github.com/aunem/transpose"
    command: go build .
    working_dir: /go/src/github.com/aunem/transpose
