version: '3'
services:
  transpose:
    build:
      context: ./
      dockerfile: Dockerfile-integration
    command: go run main.go serve
    links: 
      - server
    working_dir: /go/src/github.com/aunem/transpose
    volumes:
      - "./:/go/src/github.com/aunem/transpose"
    expose:
      - "80"
  server:
    build:
      context: ./
      dockerfile: Dockerfile-integration
    command: go run integration/server/main.go
    working_dir: /go/src/github.com/aunem/transpose
    volumes:
      - "./:/go/src/github.com/aunem/transpose"
  client:
    build:
      context: ./
      dockerfile: Dockerfile-integration
    command: go run integration/client/main.go
    links:
      - transpose
    working_dir: /go/src/github.com/aunem/transpose
    volumes:
      - "./:/go/src/github.com/aunem/transpose"
  hydra:
    image: oryd/hydra
    volumes:
      - hydravolume:/root
    ports:
      - "4444:4444"
      - "4445:4445"
    command:
      host --dangerous-auto-logon --dangerous-force-http --disable-telemetry
    environment:
      - LOG_LEVEL=debug
      - ISSUER=http://localhost:4444
      - CONSENT_URL=http://localhost:3000/consent
      - DATABASE_URL=memory
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:password
      - SYSTEM_SECRET=youReallyNeedToChangeThis
    restart: unless-stopped
